import { Router } from "express";
import { authRouter } from "./auth.routes.js";
import { restaurantRouter } from "./restaurant.routes.js";
import { categoryRouter } from "./category.routes.js";
import { menuRouter } from "./menu.routes.js";
import { modifierRouter } from "./modifier.routes.js";
import { orderRouter } from "./order.routes.js";
import { restaurantOrderRouter } from "./restaurantOrder.routes.js";
import { loyaltyRouter } from "./loyalty.routes.js";
import { userRouter } from "./user.routes.js";
import { analyticsRouter } from "./analytics.routes.js";
import { kbRouter } from "./kb.routes.js";
import { supportRouter } from "./support.routes.js";
import { restaurantSupportRouter } from "./restaurantSupport.routes.js";
import { supportAdminRouter } from "./supportAdmin.routes.js";
import { staffRouter } from "./staff.routes.js";
import { promotionRouter } from "./promotion.routes.js";
import { platformRouter } from "./platform.routes.js";
import { paymentRouter } from "./payment.routes.js";
import { paymentWebhookRouter } from "./paymentWebhook.routes.js";
import { auditLogRouter } from "./auditLog.routes.js";
import { tableRouter } from "./table.routes.js";
import { deliveryRouter } from "./delivery.routes.js";
import { geocodingRouter } from "./geocoding.routes.js";
import { customerRouter } from "./customer.routes.js";
import { uploadRouter } from "./upload.routes.js";
import { businessRouter } from "./business.routes.js";
import { businessCategoryRouter } from "./businessCategory.routes.js";
import { businessMenuRouter } from "./businessMenu.routes.js";
import { businessModifierRouter } from "./businessModifier.routes.js";
import { businessDomainRouter } from "./businessDomain.routes.js";
import { restaurantDomainRouter } from "./restaurantDomain.routes.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/users", userRouter);
apiRouter.use("/orders", orderRouter);
apiRouter.use("/businesses", businessRouter);
apiRouter.use("/businesses/:businessId/categories", businessCategoryRouter);
apiRouter.use("/businesses/:businessId/menu", businessMenuRouter);
apiRouter.use("/businesses/:businessId/menu/:menuItemId/modifiers", businessModifierRouter);
apiRouter.use("/businesses/:businessId/domains", businessDomainRouter);
apiRouter.use("/restaurants", restaurantRouter);
apiRouter.use("/restaurants/:restaurantId/domains", restaurantDomainRouter);
apiRouter.use("/restaurants/:restaurantId/categories", categoryRouter);
apiRouter.use("/restaurants/:restaurantId/menu", menuRouter);
apiRouter.use("/restaurants/:restaurantId/uploads", uploadRouter);
apiRouter.use("/restaurants/:restaurantId/menu/:menuItemId/modifiers", modifierRouter);
apiRouter.use("/restaurants/:restaurantId/orders", restaurantOrderRouter);
apiRouter.use("/restaurants/:restaurantId/orders/:orderId/payments", paymentRouter);
apiRouter.use("/webhooks/payments", paymentWebhookRouter);
apiRouter.use("/restaurants/:restaurantId/audit-log", auditLogRouter);
apiRouter.use("/restaurants/:restaurantId/tables", tableRouter);
apiRouter.use("/restaurants/:restaurantId/delivery", deliveryRouter);
apiRouter.use("/geocoding", geocodingRouter);
apiRouter.use("/restaurants/:restaurantId/loyalty", loyaltyRouter);
apiRouter.use("/restaurants/:restaurantId/staff", staffRouter);
apiRouter.use("/restaurants/:restaurantId/promotions", promotionRouter);
apiRouter.use("/platform", platformRouter);
apiRouter.use("/restaurants/:restaurantId/analytics", analyticsRouter);
apiRouter.use("/restaurants/:restaurantId/customers", customerRouter);
apiRouter.use("/restaurants/:restaurantId/support/tickets", restaurantSupportRouter);
apiRouter.use("/kb", kbRouter);
apiRouter.use("/support/admin", supportAdminRouter);
apiRouter.use("/support", supportRouter);
