import { Router } from "express";
import { authRouter } from "./auth.routes.js";
import { restaurantRouter } from "./restaurant.routes.js";
import { categoryRouter } from "./category.routes.js";
import { menuRouter } from "./menu.routes.js";
import { modifierRouter } from "./modifier.routes.js";
import { orderRouter } from "./order.routes.js";
import { restaurantOrderRouter } from "./restaurantOrder.routes.js";
import { loyaltyRouter } from "./loyalty.routes.js";
import { userRouter } from "./user.routes.js";
import { analyticsRouter } from "./analytics.routes.js";
import { kbRouter } from "./kb.routes.js";
import { supportRouter } from "./support.routes.js";
import { restaurantSupportRouter } from "./restaurantSupport.routes.js";
import { supportAdminRouter } from "./supportAdmin.routes.js";
import { staffRouter } from "./staff.routes.js";
import { promotionRouter } from "./promotion.routes.js";
import { platformRouter } from "./platform.routes.js";
import { paymentRouter } from "./payment.routes.js";
import { restaurantPaymentAccountRouter } from "./restaurantPaymentAccount.routes.js";
import { paymentWebhookRouter } from "./paymentWebhook.routes.js";
import { auditLogRouter } from "./auditLog.routes.js";
import { tableRouter } from "./table.routes.js";
import { posRouter } from "./pos.routes.js";
import { deliveryRouter } from "./delivery.routes.js";
import { deliveryDispatchRouter } from "./deliveryDispatch.routes.js";
import { restaurantDeliveryProviderAccountRouter } from "./restaurantDeliveryProviderAccount.routes.js";
import { deliveryWebhookRouter } from "./deliveryWebhook.routes.js";
import { geocodingRouter } from "./geocoding.routes.js";
import { customerRouter } from "./customer.routes.js";
import { uploadRouter } from "./upload.routes.js";
import { businessRouter } from "./business.routes.js";
import { businessCategoryRouter } from "./businessCategory.routes.js";
import { businessMenuRouter } from "./businessMenu.routes.js";
import { businessModifierRouter } from "./businessModifier.routes.js";
import { businessDomainRouter } from "./businessDomain.routes.js";
import { restaurantDomainRouter } from "./restaurantDomain.routes.js";
import { businessAnalyticsRouter } from "./businessAnalytics.routes.js";
import { businessPromotionRouter } from "./businessPromotion.routes.js";
import { businessSubscriptionRouter } from "./businessSubscription.routes.js";
import { billingWebhookRouter } from "./billingWebhook.routes.js";
import { billingMockCheckoutRouter } from "./billingMockCheckout.routes.js";
import { planRouter } from "./plan.routes.js";
import { publicPlanRouter } from "./publicPlan.routes.js";
import { agencyRouter } from "./agency.routes.js";
import { agencyMembershipRouter, agencyAcceptInviteRouter } from "./agencyMembership.routes.js";
import { agencySubscriptionRouter } from "./agencySubscription.routes.js";
import { env } from "../config/env.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/users", userRouter);
apiRouter.use("/orders", orderRouter);
apiRouter.use("/businesses", businessRouter);
apiRouter.use("/businesses/:businessId/categories", businessCategoryRouter);
apiRouter.use("/businesses/:businessId/menu", businessMenuRouter);
apiRouter.use("/businesses/:businessId/menu/:menuItemId/modifiers", businessModifierRouter);
apiRouter.use("/businesses/:businessId/domains", businessDomainRouter);
apiRouter.use("/businesses/:businessId/analytics", businessAnalyticsRouter);
apiRouter.use("/businesses/:businessId/promotions", businessPromotionRouter);
apiRouter.use("/businesses/:businessId/subscription", businessSubscriptionRouter);
apiRouter.use("/webhooks/billing", billingWebhookRouter);
// Phase 27 — only exists at all when the mock provider is active, mirroring
// businessSubscription.routes.ts's mock-advance route gating exactly.
if (env.BILLING_PROVIDER === "mock") {
  apiRouter.use("/billing/mock-checkout", billingMockCheckoutRouter);
}
apiRouter.use("/plans", planRouter);
apiRouter.use("/public/plans", publicPlanRouter);
// Phase 25 — agencies/accept-invite mounted BEFORE /agencies itself so the literal "accept-invite"
// segment can never be swallowed by /agencies/:agencyId's param matching.
apiRouter.use("/agencies/accept-invite", agencyAcceptInviteRouter);
apiRouter.use("/agencies/:agencyId/members", agencyMembershipRouter);
apiRouter.use("/agencies/:agencyId/subscription", agencySubscriptionRouter);
apiRouter.use("/agencies", agencyRouter);
apiRouter.use("/restaurants", restaurantRouter);
apiRouter.use("/restaurants/:restaurantId/domains", restaurantDomainRouter);
apiRouter.use("/restaurants/:restaurantId/categories", categoryRouter);
apiRouter.use("/restaurants/:restaurantId/menu", menuRouter);
apiRouter.use("/restaurants/:restaurantId/uploads", uploadRouter);
apiRouter.use("/restaurants/:restaurantId/menu/:menuItemId/modifiers", modifierRouter);
apiRouter.use("/restaurants/:restaurantId/orders", restaurantOrderRouter);
apiRouter.use("/restaurants/:restaurantId/orders/:orderId/payments", paymentRouter);
apiRouter.use("/restaurants/:restaurantId/orders/:orderId/delivery", deliveryDispatchRouter);
apiRouter.use("/restaurants/:restaurantId/payment-account", restaurantPaymentAccountRouter);
apiRouter.use("/restaurants/:restaurantId/delivery-account", restaurantDeliveryProviderAccountRouter);
apiRouter.use("/webhooks/payments", paymentWebhookRouter);
apiRouter.use("/webhooks/deliveries", deliveryWebhookRouter);
apiRouter.use("/restaurants/:restaurantId/audit-log", auditLogRouter);
apiRouter.use("/restaurants/:restaurantId/tables", tableRouter);
apiRouter.use("/restaurants/:restaurantId/pos", posRouter);
apiRouter.use("/restaurants/:restaurantId/delivery", deliveryRouter);
apiRouter.use("/geocoding", geocodingRouter);
apiRouter.use("/restaurants/:restaurantId/loyalty", loyaltyRouter);
apiRouter.use("/restaurants/:restaurantId/staff", staffRouter);
apiRouter.use("/restaurants/:restaurantId/promotions", promotionRouter);
apiRouter.use("/platform", platformRouter);
apiRouter.use("/restaurants/:restaurantId/analytics", analyticsRouter);
apiRouter.use("/restaurants/:restaurantId/customers", customerRouter);
apiRouter.use("/restaurants/:restaurantId/support/tickets", restaurantSupportRouter);
apiRouter.use("/kb", kbRouter);
apiRouter.use("/support/admin", supportAdminRouter);
apiRouter.use("/support", supportRouter);
